version: '3.5'

services:
  web:
    restart: always
    build: ./web
    command: gunicorn impuls.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/src/static
      - media_volume:/home/app/src/media
    expose:
      - 8000
    depends_on:
      - db
    links:
      - db
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/src/static
      - media_volume:/home/app/src/media
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    restart: always
    image: postgres:12.0-alpine
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume: