# Generated by Django 3.0.6 on 2020-05-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentimage',
            options={'verbose_name': 'Изображение инструмента', 'verbose_name_plural': 'Изображения инструмента'},
        ),
        migrations.AlterModelOptions(
            name='stanokimage',
            options={'verbose_name': 'Изображение станка', 'verbose_name_plural': 'Изображения станка'},
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='image',
        ),
    ]
