# Generated by Django 3.0.6 on 2020-05-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0002_auto_20200524_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanokgroup',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл 1'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл 2'),
        ),
        migrations.AlterField(
            model_name='instrumentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='stanokimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
