# Generated by Django 3.0.6 on 2020-06-01 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0005_auto_20200531_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instrument/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='riggingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rigging/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='stanokimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stanok/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение'),
        ),
    ]
