# Generated by Django 3.0.6 on 2020-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0006_auto_20200601_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='instrument/', verbose_name='Файл 1'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='instrument/', verbose_name='Файл 2'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manual/', verbose_name='Файл'),
        ),
    ]
