# Generated by Django 3.0.6 on 2020-06-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0007_auto_20200601_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='file',
            field=models.FileField(upload_to='manual/', verbose_name='Файл'),
        ),
    ]
