# Generated by Django 3.0.6 on 2020-06-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0008_auto_20200601_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='file2',
        ),
        migrations.CreateModel(
            name='RiggingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='rigging/', verbose_name='Файл')),
                ('rigging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='machinetools.Rigging')),
            ],
            options={
                'verbose_name': 'Файл оснастки',
                'verbose_name_plural': 'Файлы оснастки',
            },
        ),
        migrations.CreateModel(
            name='InstrumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='instrument/', verbose_name='Файл')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='machinetools.Instrument')),
            ],
            options={
                'verbose_name': 'Файл инструмента',
                'verbose_name_plural': 'Файлы инструмента',
            },
        ),
    ]
