# Generated by Django 3.0.6 on 2020-06-14 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0009_auto_20200601_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationarea',
            options={'ordering': ['name'], 'verbose_name': 'Область применения', 'verbose_name_plural': 'Области применения'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name'], 'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['name'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='processingtype',
            options={'ordering': ['name'], 'verbose_name': 'Вид обработки', 'verbose_name_plural': 'Виды обработок'},
        ),
        migrations.AlterModelOptions(
            name='rigging',
            options={'ordering': ['name'], 'verbose_name': 'Оснастка', 'verbose_name_plural': 'Оснастки'},
        ),
        migrations.AlterModelOptions(
            name='riggingtype',
            options={'ordering': ['name'], 'verbose_name': 'Вид оснастки', 'verbose_name_plural': 'Виды оснасток'},
        ),
        migrations.AlterModelOptions(
            name='stanok',
            options={'ordering': ['group'], 'verbose_name': 'Станок', 'verbose_name_plural': 'Станки'},
        ),
        migrations.AlterModelOptions(
            name='stanokgroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа станков', 'verbose_name_plural': 'Группы станков'},
        ),
        migrations.AlterModelOptions(
            name='workpiecetype',
            options={'ordering': ['name'], 'verbose_name': 'Вид обрабатываемой детали', 'verbose_name_plural': 'Виды обрабатываемой детали'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rigging',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stanok',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stanokgroup',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
