# Generated by Django 3.0.6 on 2020-06-14 12:00

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinetools', '0011_auto_20200614_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernBladeProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('preview', models.ImageField(upload_to='modern_blade_processing/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Превью')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Современная лезвийная обработка',
                'verbose_name_plural': 'Современные лезвийные обработки',
                'ordering': ['name'],
            },
        ),
    ]
